# Q1

In [1]:
import numpy as np
a=np.array([1,7,3,9,5])
b=np.array([6,2,8,4,5])

In [2]:
print(a[a>b])

[7 9]


In [3]:
print(a[a>=b])

[7 9 5]


In [4]:
print(b[a<b])

[6 8]


In [5]:
print(b[a<=b])

[6 8 5]


# Q2

In [6]:
c=np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
d=np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
e=np.full(10,5)
e

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Q3

In [9]:
s=np.add(a,b)
s

array([ 7,  9, 11, 13, 10])

In [10]:
a1 = np.array([[11,12,13,14], [21,22,23,24]])
a1

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [11]:
print("Sum of each column:")
print(np.sum(a1, axis=0))
print("Sum of each row:")
print(np.sum(a1, axis=1))


Sum of each column:
[32 34 36 38]
Sum of each row:
[50 90]


# Q4

In [12]:
x=np.array([1,7,3,9,5])
y=np.array([6,2,8,4,5])

In [13]:
print(np.add(x, y))

[ 7  9 11 13 10]


In [14]:
print(np.subtract(x, y))

[-5  5 -5  5  0]


In [15]:
print(np.multiply(x, y))

[ 6 14 24 36 25]


In [16]:
print(np.divide(x, y))

[0.16666667 3.5        0.375      2.25       1.        ]


# Q5

In [17]:
k=np.array([0,30,45,60,90])

In [18]:
np.sin(k)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [19]:
np.cos(k)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [20]:
np.tan(k)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

# Q6

In [21]:
import pandas as pd


In [22]:
df1 = pd.DataFrame({'id': ['1', '2', '3', '4'],
                        'names': ['a', 'b', 'c', 'd'],
                        'scores': ['100', '200', '150', '50']})
df1

id names scores
0  1     a    100
1  2     b    200
2  3     c    150
3  4     d     50

In [23]:
print(df1['names'])
print(df1['scores'])

0    a
1    b
2    c
3    d
Name: names, dtype: object
0    100
1    200
2    150
3     50
Name: scores, dtype: object


# Q7

In [25]:
df2 = pd.DataFrame({'id': ['5', '6', '7', '8'],
                        'names': ['a1', 'b1', 'c1', 'd1'],
                        'scores': ['60', '20', '50', '70']})
df2                       

id names scores
0  5    a1     60
1  6    b1     20
2  7    c1     50
3  8    d1     70

In [26]:
pd.concat([df1,df2],axis=1)

id names scores id names scores
0  1     a    100  5    a1     60
1  2     b    200  6    b1     20
2  3     c    150  7    c1     50
3  4     d     50  8    d1     70

# Q8

In [28]:
df3 = pd.DataFrame({'id': ['9', '10', '11', '12'],
                    'names': ['a2', 'b2',np.nan, 'd2'],
                    'scores': ['50', '70',np.nan,np.nan]})
df3


id names scores
0   9    a2     50
1  10    b2     70
2  11   NaN    NaN
3  12    d2    NaN

# Q9

In [29]:
df3.isnull()

id  names  scores
0  False  False   False
1  False  False   False
2  False   True    True
3  False  False    True

# Q10

In [30]:
data = [1, 2, 3, 4, 5] 
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64